"""Bootstrap this repository's AGENTS.md from a versioned development policy."""

import argparse
import json
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
policy = json.loads((root / "docs/repository-policy.json").read_text(encoding="utf-8"))
content = "\n".join(
    [
        f"# {policy['title']}",
        "",
        "Generated from docs/repository-policy.json by scripts/generate_repo_agents.py.",
        "Edit the source policy and regenerate; do not edit this file manually.",
        "This bootstrap policy is separate from harnesses generated for target projects.",
        "",
        policy["purpose"],
        "",
        "## Rules",
        "",
        *(f"- {rule}" for rule in policy["rules"]),
        "",
        "## Checks",
        "",
        "```sh",
        *policy["checks"],
        "```",
        "",
    ]
)
target = root / "AGENTS.md"
if args.check:
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        raise SystemExit("AGENTS.md is stale; run uv run python scripts/generate_repo_agents.py")
else:
    target.write_text(content, encoding="utf-8", newline="\n")
print("Repository instructions are current.")
